services:
  helios-db:
    container_name: helios-db
    image: postgres:12.4
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U helios -d helios"]
      interval: 30s
      retries: 5
      start_period: 30s
      timeout: 30s
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PWD}
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - helios-pgdata:/var/lib/postgresql/data/pgdata
    networks:
      - helios-network
  helios-celery:
    container_name: helios-celery
    image: registry.davicoelho.com/sistemas/helios:${TAG}
    env_file:
      - .env
    command: celery worker --app helios --events --beat --concurrency 8 --logfile celeryw.log --pidfile celeryw.pid
    depends_on:
      helios-db:
        condition: service_healthy
        restart: true
      helios-rabbitmq:
        condition: service_healthy
        restart: true
    networks:
      - helios-network
  helios-rabbitmq:
    container_name: helios-rabbitmq
    image: rabbitmq:3-management-alpine
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      retries: 5
      start_period: 30s
      timeout: 30s
    volumes:
      - helios-rabbitmq-data:/var/lib/rabbitmq/
      - helios-rabbitmq-log:/var/log/rabbitmq
    networks:
      - helios-network
  helios-server:
    container_name: helios-server
    image: registry.davicoelho.com/sistemas/helios:${TAG}
    env_file:
      - .env
    command: apache2ctl -D FOREGROUND
    depends_on:
      helios-db:
        condition: service_healthy
        restart: true
    expose:
     - "80"
    labels:
     - "traefik.enable=true"
     - "traefik.http.routers.helios-server.rule=Host(`helios.davicoelho.com`)"
     - "traefik.http.routers.helios-server.tls=true"
     - "traefik.http.routers.helios-server.tls.certresolver=lets-encrypt"
    networks:
      - helios-network
      - web

volumes:
  helios-pgdata:
    name: helios-pgdata
  helios-rabbitmq-data:
    name: helios-rabbitmq-data
  helios-rabbitmq-log:
    name: helios-rabbitmq-log

networks:
  web:
    external: true
  helios-network:
    name: helios-network
