# Para gerar o site estático: mkdocs build
# Para rodar um servidor para testes: mkdocs serve

site_name: Helios - Sistema de votação eletrônica
site_description: 'Ajuda do sistema de votação eletrônica'
site_author: 'Instituto Federal de Santa Catarina'
copyright: 'Copyright &copy; 2018 - IFSC'

nav:
    - Como votar: index.md

theme:
  name: 'material'
  include_sidebar: false
  custom_dir: 'theme'
  logo:
    icon: 'home'
  language: pt
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  feature:
    - search.suggest
    - search.highlight
    - search.share
    - navigation.tabs
    - navigation.instant
    - navigation.tracking
    - navigation.top
  extra:
  search:
    language: 'pt'
